# mod properties
mod_version=1.4
maven_group=com.danz
archives_base_name=autocrop
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.19.2
fabric_version=0.114.1+1.21.3
cloth_config_version=16.0.141
modmenu_version=13.0.1

# gradle build settings
org.gradle.parallel=true
org.gradle.caching=true
